#! /bin/bash

# gstawk *.fa
# gstawk -x assembly.fa
# gstawk -c CTGCAG assembly.fa

# Defaults
C=""
J=1
X=0

while getopts c:j:x opt
do
    case $opt in
	c) C=$OPTARG;;
	j) J=$OPTARG;;
	x) X=1;;
    esac
done

INDEX=$(($OPTIND))
FILES="${@:$INDEX}"

wrkdir=$(pwd)
makedir=$(dirname $(readlink -f "$0"))

if [ "$C" != "" ]
then
    $makedir/bin/grep.o $C $FILES
else
    if [ $X -eq 1 ]
    then
	$makedir/bin/nx.o $FILES
    else
	FILELOG=$wrkdir"/".gstawk.log
	echo $FILES > $FILELOG
	make -j $J -f gstawk_make -C $makedir -s stats FILENAMES=$FILELOG PWD=$wrkdir
	make -f gstawk_make -C $makedir -s print FILENAMES=$FILELOG PWD=$wrkdir
    fi
fi
